/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.CardLayout;

/**
 *
 * @author Fajar
 */
public class GambarButton extends javax.swing.JFrame {

    /**
     * Creates new form GambarButton
     */
    public GambarButton() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gambar = new javax.swing.JPanel();
        messibtn = new javax.swing.JButton();
        mbappebtn = new javax.swing.JButton();
        ronaldobtn = new javax.swing.JButton();
        exitbtn = new javax.swing.JButton();
        imagepanel = new javax.swing.JPanel();
        Messi = new javax.swing.JLabel();
        Mbappe = new javax.swing.JLabel();
        Ronaldo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        gambar.setBackground(new java.awt.Color(153, 153, 255));

        messibtn.setText("Messi");
        messibtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messibtnActionPerformed(evt);
            }
        });

        mbappebtn.setText("Mbappe");
        mbappebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbappebtnActionPerformed(evt);
            }
        });

        ronaldobtn.setText("Ronaldo");
        ronaldobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ronaldobtnActionPerformed(evt);
            }
        });

        exitbtn.setText("Exit");
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gambarLayout = new javax.swing.GroupLayout(gambar);
        gambar.setLayout(gambarLayout);
        gambarLayout.setHorizontalGroup(
            gambarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gambarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(messibtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(mbappebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(ronaldobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(exitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(3274, Short.MAX_VALUE))
        );
        gambarLayout.setVerticalGroup(
            gambarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gambarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gambarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(messibtn)
                    .addComponent(mbappebtn)
                    .addComponent(ronaldobtn)
                    .addComponent(exitbtn))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        getContentPane().add(gambar, java.awt.BorderLayout.PAGE_START);

        imagepanel.setLayout(new java.awt.CardLayout());

        Messi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Messi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Messi.jpg"))); // NOI18N
        imagepanel.add(Messi, "0");

        Mbappe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Mbappe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/kylian-mbappe-1_169.jpeg"))); // NOI18N
        Mbappe.setToolTipText("");
        Mbappe.setPreferredSize(new java.awt.Dimension(550, 550));
        imagepanel.add(Mbappe, "1");

        Ronaldo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ronaldo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/efek-cristiano-ronaldo-harga-tiket-laga-man-united-vs-newcastle-melambung-tinggi-peL8JcXuld.jpeg"))); // NOI18N
        imagepanel.add(Ronaldo, "2");

        getContentPane().add(imagepanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void messibtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messibtnActionPerformed
        CardLayout cl = (CardLayout) (imagepanel.getLayout());
        cl.show(imagepanel,"0");
    }//GEN-LAST:event_messibtnActionPerformed

    private void mbappebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbappebtnActionPerformed
       CardLayout cl = (CardLayout) (imagepanel.getLayout());
       cl.show(imagepanel,"1");
    }//GEN-LAST:event_mbappebtnActionPerformed

    private void ronaldobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ronaldobtnActionPerformed
        CardLayout cl = (CardLayout) (imagepanel.getLayout());
        cl.show(imagepanel,"2");
    }//GEN-LAST:event_ronaldobtnActionPerformed

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GambarButton().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Mbappe;
    private javax.swing.JLabel Messi;
    private javax.swing.JLabel Ronaldo;
    private javax.swing.JButton exitbtn;
    private javax.swing.JPanel gambar;
    private javax.swing.JPanel imagepanel;
    private javax.swing.JButton mbappebtn;
    private javax.swing.JButton messibtn;
    private javax.swing.JButton ronaldobtn;
    // End of variables declaration//GEN-END:variables
}
